version: "3.8"

services:
  devcontainer:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/workspace
      - ~/.ssh:/home/vscode/.ssh:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
