version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /home/vscode/app
    volumes:
      - ./app:/home/vscode/app:rw
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
