FROM mcr.microsoft.com/devcontainers/base:bullseye

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.12.3.zip" -o "awscliv2.zip"\
    && unzip awscliv2.zip && sudo ./aws/install

RUN wget https://github.com/aws/aws-sam-cli/releases/download/v1.89.0/aws-sam-cli-linux-x86_64.zip\ 
    && unzip aws-sam-cli-linux-x86_64.zip -d sam-installation && sudo ./sam-installation/install

RUN sudo apt-get update && sudo apt update \
    && sudo apt-get install -y python3-pip=20.3.4-4+deb11u1